spring.application.name=ia-para-requisitos
spring.ai.openai.api-key={API_CHAVE}
spring.ai.openai.base-url={API_URL}
spring.ai.openai.chat.completions-path={FINAL_URL}
spring.ai.openai.chat.options.model={MODELO_IA}
